"""Time-of-day greeting + short positive motivational lines.

The quote pool is intentionally broker-friendly: mild, encouraging,
professional. No religion, no politics, no generic self-help buzzwords.
"""
from __future__ import annotations

import random
from datetime import datetime


QUOTES: tuple[str, ...] = (
    "Today is a great day to close a deal.",
    "Small steps every day add up to big results.",
    "Your attention to detail makes the difference.",
    "Every statement you review helps a family find a home.",
    "Calm focus beats frantic effort.",
    "Careful work today saves headaches tomorrow.",
    "You've got this.",
    "One client at a time — that's how the best brokers do it.",
    "Your expertise is someone's peace of mind.",
    "Progress, not perfection.",
    "Take a breath. Then take the next step.",
    "Clarity comes from doing.",
    "Trust your process — it's working.",
    "Great brokers are great listeners.",
    "A tidy ledger is a tidy mind.",
    "Keep it simple. Keep it accurate.",
    "Your clients trust you for a reason.",
    "Steady wins the week.",
    "Small wins build big confidence.",
    "You make complicated things feel simple.",
    "Stay curious — every case teaches something.",
    "Professional, patient, precise.",
    "Your discipline today pays tomorrow.",
    "Finish strong.",
    "You turn paperwork into opportunity.",
    "Each reviewed statement is one step closer to completion.",
    "Good work travels far — keep at it.",
    "The right answer is usually the careful one.",
    "You're closer than you think.",
    "Nothing tops honest numbers done well.",
    "Consistency is the quiet superpower.",
    "Quality over speed, always.",
    "Your clients feel your care.",
    "Start simple. Build from there.",
    "Do the basics brilliantly.",
    "One file at a time.",
    "You bring order to the numbers.",
    "Steady hands, clear head.",
    "A careful broker is a trusted broker.",
    "You make the paperwork feel painless.",
    "Focus beats firepower.",
    "Today counts.",
    "Your reputation is built one case at a time.",
    "Patience is a form of skill.",
    "Organise the chaos — that's where you shine.",
    "Great decisions come from good data.",
    "Precision is a kindness to your future self.",
    "You're quietly excellent at this.",
    "Take the time. It's worth it.",
    "Every correction teaches the system.",
    "Let the details do the talking.",
    "Clean numbers, clear conscience.",
    "Keep going — you're doing great.",
    "Trust yourself. The numbers do too.",
    "Every good broker starts with good records.",
    "Detail is where the magic happens.",
    "Calm beats clever.",
    "Precision is a form of respect.",
    "One correct category at a time.",
    "Your thoroughness is your edge.",
    "Right first time, every time.",
    "Careful eyes, happy clients.",
    "Keep it tidy, keep it true.",
    "Today's effort, tomorrow's outcome.",
    "A good broker is a patient broker.",
    "Make it clean, make it clear.",
    "You see what others miss.",
    "Your work moves people into homes.",
    "Bit by bit, the picture emerges.",
    "Steady as you go.",
    "Attention pays compound interest.",
    "Patient brokers build strong books.",
    "You're the reason this gets done properly.",
    "Keep it meticulous.",
    "Small improvements, every day.",
    "Another statement done — well done.",
    "Your clients appreciate you, even when they forget to say it.",
    "Be the broker you'd want to hire.",
    "Honest numbers, clear advice.",
    "Concentrate and conquer.",
    "A calm broker is a confident broker.",
    "Finish what's in front of you.",
    "Make today count.",
    "Let the evidence lead you.",
    "You're building something real.",
    "Every review makes tomorrow easier.",
    "Careful categories, confident conclusions.",
    "Trust the process you've built.",
    "Your standards lift the whole practice.",
    "Step by step, case by case.",
    "Your diligence is a gift.",
    "Keep your eye on the detail.",
    "You handle pressure with grace.",
    "Stay with it — you're almost there.",
    "A good broker makes clients feel safe.",
    "One well-reviewed file at a time.",
    "Patience shows up in the numbers.",
    "Your quiet rigour is a competitive advantage.",
    "Consistent beats clever every time.",
    "Keep showing up — that's most of it.",
    "You're doing the work that matters.",
    "Well begun is half done.",
    "Do it once, do it right.",
    "Every step forward counts.",
    "Be kind to yourself — this is hard work.",
    "You turn pressure into output.",
    "The best brokers finish what they start.",
    "You earn trust one category at a time.",
    "Clarity is a service you provide.",
    "Another day, another well-reviewed file.",
    "Good numbers make good decisions.",
    "Your care shows up in the export.",
    "Your accuracy makes you indispensable.",
    "Keep the focus. Keep the standards.",
    "Quiet professionals change lives.",
    "Every detail is an act of care.",
    "Keep going — the end is closer than it looks.",
    "Patience and precision — your winning combination.",
    "Treat the numbers well and they'll treat you well.",
    "You always find the right answer eventually.",
    "It's a good day to get organised.",
    "Simple, accurate, done.",
    "Nothing beats an honest afternoon's work.",
    "Clarity is a habit — you've got it.",
    "Take pride in the small stuff.",
    "You're building a reputation — one file at a time.",
    "Stay patient. Stay precise.",
    "Another client helped — nicely done.",
    "Smooth is fast.",
    "Respect the detail and the detail respects you.",
    "One careful choice at a time.",
    "You keep this practice running.",
    "Your work has real impact.",
    "The best brokers care about the numbers.",
    "You're the reason people get approved.",
    "Everything you do matters.",
    "Give today your best — it usually is.",
    "Refuse to rush. Refuse to cut corners.",
    "Calm and careful wins the week.",
    "Today you get to help someone.",
    "A tidy workflow is a peaceful workflow.",
    "You keep the standards high.",
    "Keep your standards up — even when nobody's watching.",
    "Every review is a vote for quality.",
    "Detail is your superpower.",
    "Keep polishing. Keep improving.",
    "Your dedication is felt.",
    "You're making someone's dream possible.",
    "The hard part is starting — and you already have.",
    "Take it row by row.",
    "Kind rigour — that's the broker's way.",
    "Slow down to speed up.",
    "Excellence is a series of small choices.",
    "Every pass improves the outcome.",
    "Careful categories, confident clients.",
    "Keep solving the puzzle — you're nearly there.",
    "You are the steady hand this file needs.",
    "Make the numbers sing.",
    "A good broker trusts the detail.",
    "You handle the numbers so clients don't have to.",
    "Your focus is a gift to your clients.",
    "You do the quiet work that matters.",
    "Each transaction, each category — your craft.",
    "Meticulous is a compliment.",
    "Your effort today will mean a keys-in-hand moment for someone.",
    "Keep listening to the data.",
    "Good brokers finish the job.",
    "Deep work beats busy work.",
    "You make complex feel manageable.",
    "Each file is a story — you help write the happy ending.",
    "You deliver the truth kindly.",
    "Another good review in the books.",
    "Your steady pace wins.",
    "Let the numbers tell the story.",
    "You translate statements into possibilities.",
    "Careful in, confident out.",
    "You show up and get it done.",
    "The effort you put in is visible.",
    "Patience is your edge.",
    "Stay calm, stay careful.",
    "One more careful review — that's all it takes.",
    "You handle this beautifully.",
    "Steady work is strong work.",
    "Trust what you see. Verify what you don't.",
    "You're better at this than you give yourself credit for.",
    "Your quiet diligence is powerful.",
    "Rigour is kindness in disguise.",
    "Today's small correction is tomorrow's auto-category.",
    "You're teaching the system as you work.",
    "Every correction makes the next file faster.",
    "Your care compounds.",
    "Let's make today a clean sweep.",
    "A clear statement is a happy statement.",
    "Enjoy the rhythm of good work.",
    "Every review brings a family closer to a home.",
    "Calm focus is your default.",
    "You know what good looks like.",
    "Your book of business reflects your care.",
    "Keep noticing the details.",
    "Today's file is tomorrow's success story.",
    "Kind, calm, careful — that's you.",
    "Good work, every time.",
    "Your numbers are tight — I can tell.",
    "Careful brokers sleep well.",
)


def _time_of_day(now: datetime | None = None) -> str:
    now = now or datetime.now()
    hour = now.hour
    if hour < 12:
        return "morning"
    if hour < 18:
        return "afternoon"
    return "evening"


def greeting_for(display_name: str, *, now: datetime | None = None) -> str:
    """Return 'Good morning, Jane' (etc.) based on the local clock."""
    part = _time_of_day(now)
    clean = (display_name or "").strip() or "there"
    return f"Good {part}, {clean}"


def random_quote(rng: random.Random | None = None) -> str:
    r = rng or random
    return r.choice(QUOTES)
